### ISSUE TITLE
SetField superclass should be changed to support type-changing updates

### ISSUE THREAD

**Issue by aavogt** [trskop/overloaded-records#1]
This file doesn't compile: http://lpaste.net/4592543611182120960 , but I think it should without changing the parts I copy-pasted from Data/OverloadedRecords.hs

I think it should be more like:

``` haskell
class 
   ( FieldType l (UpdateType l s) ~ b
    ) => SetField l s b
```

**Comment by trskop** [comment]
Thanks for your report. I'll try to get in to it as soon as possible.

**Comment by trskop** [comment]
It won't be that easy. Constraint `FieldType l (UpdateType l s b) ~ b` is ambiguous due to the fact that type families aren't injective. GHC 8 has injective type families, but I need this library to work on older versions, as well.

**Comment by aavogt** [comment]
https://gist.github.com/aavogt/970b892c78a686ca8ee2 shows how that constraint helps ghc work out `b` given `UpdateType l s b` and `l`. Can you come up with a scenario where having a `FieldType l (UpdateType l s b) ~ b` makes inferred types worse?

https://ghc.haskell.org/trac/ghc/ticket/10009 is probably the reason it doesn't work with ghc-7.10

**Comment by trskop** [comment]
Problem is not what types it inferred, but that it wasn't able to infer types in some normal use cases without a hint. We use this library at my work and I've just refactored 25+ KLOC code base to use it. I'll try to experiment with this during our short downtime at the end of a sprint to see if it breaks anything or requires too much additional type annotations.

Meanwhile I've come up with alternative approach that may work, but I hadn't used it in anger yet. The core idea is a switch from `SetField` type class to `ModifyField`, which is parametrized with all the type variables:

``` Haskell
class (HasField l s a) => ModifyField (l :: Symbol) s t a b
    | l s -> a, l t -> b, l s b -> t, l t a -> s
  where
    {-# MINIMAL modifyField | setField #-}

    modifyField :: Proxy# l -> (a -> b) -> s -> t
    modifyField proxy f s = setField proxy s (f (getField proxy s))

    setField :: Proxy# l -> s -> b -> t
    setField proxy s b = modifyField proxy (const b) s
```

Type of `modifyField` is not too far from a lens type signature, so maybe that should be included as well. It would allow users to provide their own definition, which may be more effective in some cases.

I've included your use-case scenario in unit tests and it seems to work. I would be grateful if you could experiment with that as well. I really need to catch on my sleep. :-)

**Comment by aavogt** [comment]
Here's why I think `ModifyField` won't do any better: setField doesn't mention the `a` type, so that means the `l s -> a` FD needs to be used. When `a` is known it can be an input to `l t a -> s`, but we already needed to know `s` to get `a` from the other FD, so those two new FDs don't add anything. The other two FDs express the same thing you tried: `(FieldType l t ~ b, UpdateType l s b ~ t)`.

I think your application code need to be changed to specify (s ~ t, a ~ b) in some cases, maybe by adding in a Control.Lens.simple or maybe defining a different setField.

**Comment by trskop** [comment]
You're assuming that we use `setField`, we actually use lenses for most of our work and `IsFieldAccessor` instance for that mentions all variables:

``` Haskell
-- | Overloaded lens:
--
-- @
-- 'Functor' f => 'Proxy#' l -> (a -> f b) -> s -> f t
-- @
instance
    ( Functor f
    , ModifyField l s t a b
    ) => IsFieldAccessor l (a -> f b) (s -> f t) 'True
  where
    fieldAccessor proxy f s = setField proxy s <$> f (getField proxy s)
```

In such setting `setField` becomes just a convenient way of defining `ModifyField` instances.

**Comment by trskop** [comment]
I would be grateful if you could provide code examples that demonstrate potential issues. It would really help with building up a foolproof set of unit tests.
